# Generated by Django 3.2.9 on 2021-12-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211128_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'Organizacja pozarządowa'), (2, 'Zbiórka lokalna'), (0, 'Fundacja')], default=0),
        ),
    ]
